# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class Column(Model):
    """A table column.

    A column in a table.

    :param name: The name of this column.
    :type name: str
    :param type: The data type of this column.
    :type type: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Column, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.type = kwargs.get('type', None)


class ErrorDetail(Model):
    """Error details.

    All required parameters must be populated in order to send to Azure.

    :param code: Required. The error's code.
    :type code: str
    :param message: Required. A human readable error message.
    :type message: str
    :param target: Indicates which property in the request is responsible for
     the error.
    :type target: str
    :param value: Indicates which value in 'target' is responsible for the
     error.
    :type value: str
    :param resources: Indicates resources which were responsible for the
     error.
    :type resources: list[str]
    :param additional_properties:
    :type additional_properties: object
    """

    _validation = {
        'code': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
        'resources': {'key': 'resources', 'type': '[str]'},
        'additional_properties': {'key': 'additionalProperties', 'type': 'object'},
    }

    def __init__(self, **kwargs):
        super(ErrorDetail, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)
        self.target = kwargs.get('target', None)
        self.value = kwargs.get('value', None)
        self.resources = kwargs.get('resources', None)
        self.additional_properties = kwargs.get('additional_properties', None)


class ErrorInfo(Model):
    """The code and message for an error.

    All required parameters must be populated in order to send to Azure.

    :param code: Required. A machine readable error code.
    :type code: str
    :param message: Required. A human readable error message.
    :type message: str
    :param details: error details.
    :type details: list[~azure.loganalytics.models.ErrorDetail]
    :param innererror: Inner error details if they exist.
    :type innererror: ~azure.loganalytics.models.ErrorInfo
    :param additional_properties:
    :type additional_properties: object
    """

    _validation = {
        'code': {'required': True},
        'message': {'required': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'details': {'key': 'details', 'type': '[ErrorDetail]'},
        'innererror': {'key': 'innererror', 'type': 'ErrorInfo'},
        'additional_properties': {'key': 'additionalProperties', 'type': 'object'},
    }

    def __init__(self, **kwargs):
        super(ErrorInfo, self).__init__(**kwargs)
        self.code = kwargs.get('code', None)
        self.message = kwargs.get('message', None)
        self.details = kwargs.get('details', None)
        self.innererror = kwargs.get('innererror', None)
        self.additional_properties = kwargs.get('additional_properties', None)


class ErrorResponse(Model):
    """Error details.

    Contains details when the response code indicates an error.

    All required parameters must be populated in order to send to Azure.

    :param error: Required. The error details.
    :type error: ~azure.loganalytics.models.ErrorInfo
    """

    _validation = {
        'error': {'required': True},
    }

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorInfo'},
    }

    def __init__(self, **kwargs):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = kwargs.get('error', None)


class ErrorResponseException(HttpOperationError):
    """Server responsed with exception of type: 'ErrorResponse'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(ErrorResponseException, self).__init__(deserialize, response, 'ErrorResponse', *args)


class MetadataApplication(Model):
    """MetadataApplication.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param resource_id: Required.
    :type resource_id: str
    :param name: Required.
    :type name: str
    :param region: Required.
    :type region: str
    :param related:
    :type related: ~azure.loganalytics.models.MetadataApplicationRelated
    """

    _validation = {
        'id': {'required': True},
        'resource_id': {'required': True},
        'name': {'required': True},
        'region': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'region': {'key': 'region', 'type': 'str'},
        'related': {'key': 'related', 'type': 'MetadataApplicationRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataApplication, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.resource_id = kwargs.get('resource_id', None)
        self.name = kwargs.get('name', None)
        self.region = kwargs.get('region', None)
        self.related = kwargs.get('related', None)


class MetadataApplicationRelated(Model):
    """MetadataApplicationRelated.

    :param tables:
    :type tables: list[str]
    :param functions:
    :type functions: list[str]
    """

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataApplicationRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.functions = kwargs.get('functions', None)


class MetadataCategory(Model):
    """MetadataCategory.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param display_name: Required.
    :type display_name: str
    :param description:
    :type description: str
    :param related:
    :type related: ~azure.loganalytics.models.MetadataCategoryRelated
    """

    _validation = {
        'id': {'required': True},
        'display_name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'related': {'key': 'related', 'type': 'MetadataCategoryRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataCategory, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.related = kwargs.get('related', None)


class MetadataCategoryRelated(Model):
    """MetadataCategoryRelated.

    :param tables:
    :type tables: list[str]
    :param functions:
    :type functions: list[str]
    :param resource_types:
    :type resource_types: list[str]
    :param queries:
    :type queries: list[str]
    :param solutions:
    :type solutions: list[str]
    """

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[str]'},
        'queries': {'key': 'queries', 'type': '[str]'},
        'solutions': {'key': 'solutions', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataCategoryRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.functions = kwargs.get('functions', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.queries = kwargs.get('queries', None)
        self.solutions = kwargs.get('solutions', None)


class MetadataFunction(Model):
    """MetadataFunction.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param parameters:
    :type parameters: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param body: Required.
    :type body: str
    :param tags:
    :type tags: object
    :param properties:
    :type properties: object
    :param related:
    :type related: ~azure.loganalytics.models.MetadataFunctionRelated
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'body': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'body': {'key': 'body', 'type': 'str'},
        'tags': {'key': 'tags', 'type': 'object'},
        'properties': {'key': 'properties', 'type': 'object'},
        'related': {'key': 'related', 'type': 'MetadataFunctionRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataFunction, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.parameters = kwargs.get('parameters', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.body = kwargs.get('body', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)
        self.related = kwargs.get('related', None)


class MetadataFunctionRelated(Model):
    """MetadataFunctionRelated.

    :param tables:
    :type tables: list[str]
    :param solutions:
    :type solutions: list[str]
    :param resource_types:
    :type resource_types: list[str]
    :param categories:
    :type categories: list[str]
    :param workspaces:
    :type workspaces: list[str]
    """

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'solutions': {'key': 'solutions', 'type': '[str]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[str]'},
        'categories': {'key': 'categories', 'type': '[str]'},
        'workspaces': {'key': 'workspaces', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataFunctionRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.solutions = kwargs.get('solutions', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.categories = kwargs.get('categories', None)
        self.workspaces = kwargs.get('workspaces', None)


class MetadataPermissions(Model):
    """MetadataPermissions.

    All required parameters must be populated in order to send to Azure.

    :param workspaces: Required.
    :type workspaces:
     list[~azure.loganalytics.models.MetadataPermissionsWorkspacesItem]
    :param resources:
    :type resources:
     list[~azure.loganalytics.models.MetadataPermissionsResourcesItem]
    :param applications:
    :type applications:
     list[~azure.loganalytics.models.MetadataPermissionsApplicationsItem]
    """

    _validation = {
        'workspaces': {'required': True},
    }

    _attribute_map = {
        'workspaces': {'key': 'workspaces', 'type': '[MetadataPermissionsWorkspacesItem]'},
        'resources': {'key': 'resources', 'type': '[MetadataPermissionsResourcesItem]'},
        'applications': {'key': 'applications', 'type': '[MetadataPermissionsApplicationsItem]'},
    }

    def __init__(self, **kwargs):
        super(MetadataPermissions, self).__init__(**kwargs)
        self.workspaces = kwargs.get('workspaces', None)
        self.resources = kwargs.get('resources', None)
        self.applications = kwargs.get('applications', None)


class MetadataPermissionsApplicationsItem(Model):
    """MetadataPermissionsApplicationsItem.

    All required parameters must be populated in order to send to Azure.

    :param resource_id: Required.
    :type resource_id: str
    """

    _validation = {
        'resource_id': {'required': True},
    }

    _attribute_map = {
        'resource_id': {'key': 'resourceId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(MetadataPermissionsApplicationsItem, self).__init__(**kwargs)
        self.resource_id = kwargs.get('resource_id', None)


class MetadataPermissionsResourcesItem(Model):
    """MetadataPermissionsResourcesItem.

    All required parameters must be populated in order to send to Azure.

    :param resource_id: Required.
    :type resource_id: str
    :param deny_tables:
    :type deny_tables: list[str]
    """

    _validation = {
        'resource_id': {'required': True},
    }

    _attribute_map = {
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'deny_tables': {'key': 'denyTables', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataPermissionsResourcesItem, self).__init__(**kwargs)
        self.resource_id = kwargs.get('resource_id', None)
        self.deny_tables = kwargs.get('deny_tables', None)


class MetadataPermissionsWorkspacesItem(Model):
    """MetadataPermissionsWorkspacesItem.

    All required parameters must be populated in order to send to Azure.

    :param resource_id: Required.
    :type resource_id: str
    :param deny_tables:
    :type deny_tables: list[str]
    """

    _validation = {
        'resource_id': {'required': True},
    }

    _attribute_map = {
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'deny_tables': {'key': 'denyTables', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataPermissionsWorkspacesItem, self).__init__(**kwargs)
        self.resource_id = kwargs.get('resource_id', None)
        self.deny_tables = kwargs.get('deny_tables', None)


class MetadataQuery(Model):
    """MetadataQuery.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param body: Required.
    :type body: str
    :param labels:
    :type labels: list[str]
    :param tags:
    :type tags: object
    :param properties:
    :type properties: object
    :param related:
    :type related: ~azure.loganalytics.models.MetadataQueryRelated
    """

    _validation = {
        'id': {'required': True},
        'body': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'body': {'key': 'body', 'type': 'str'},
        'labels': {'key': 'labels', 'type': '[str]'},
        'tags': {'key': 'tags', 'type': 'object'},
        'properties': {'key': 'properties', 'type': 'object'},
        'related': {'key': 'related', 'type': 'MetadataQueryRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataQuery, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.body = kwargs.get('body', None)
        self.labels = kwargs.get('labels', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)
        self.related = kwargs.get('related', None)


class MetadataQueryRelated(Model):
    """MetadataQueryRelated.

    :param categories:
    :type categories: list[str]
    :param solutions:
    :type solutions: list[str]
    :param resource_types:
    :type resource_types: list[str]
    :param tables:
    :type tables: list[str]
    """

    _attribute_map = {
        'categories': {'key': 'categories', 'type': '[str]'},
        'solutions': {'key': 'solutions', 'type': '[str]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[str]'},
        'tables': {'key': 'tables', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataQueryRelated, self).__init__(**kwargs)
        self.categories = kwargs.get('categories', None)
        self.solutions = kwargs.get('solutions', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.tables = kwargs.get('tables', None)


class MetadataResourceType(Model):
    """MetadataResourceType.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param type: Required.
    :type type: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param labels:
    :type labels: list[str]
    :param tags:
    :type tags: object
    :param properties:
    :type properties: object
    :param related:
    :type related: ~azure.loganalytics.models.MetadataResourceTypeRelated
    """

    _validation = {
        'id': {'required': True},
        'type': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'labels': {'key': 'labels', 'type': '[str]'},
        'tags': {'key': 'tags', 'type': 'object'},
        'properties': {'key': 'properties', 'type': 'object'},
        'related': {'key': 'related', 'type': 'MetadataResourceTypeRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataResourceType, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.type = kwargs.get('type', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.labels = kwargs.get('labels', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)
        self.related = kwargs.get('related', None)


class MetadataResourceTypeRelated(Model):
    """MetadataResourceTypeRelated.

    :param tables:
    :type tables: list[str]
    :param functions:
    :type functions: list[str]
    :param categories:
    :type categories: list[str]
    :param queries:
    :type queries: list[str]
    :param workspaces:
    :type workspaces: list[str]
    :param resources:
    :type resources: list[str]
    """

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
        'categories': {'key': 'categories', 'type': '[str]'},
        'queries': {'key': 'queries', 'type': '[str]'},
        'workspaces': {'key': 'workspaces', 'type': '[str]'},
        'resources': {'key': 'resources', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataResourceTypeRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.functions = kwargs.get('functions', None)
        self.categories = kwargs.get('categories', None)
        self.queries = kwargs.get('queries', None)
        self.workspaces = kwargs.get('workspaces', None)
        self.resources = kwargs.get('resources', None)


class MetadataResults(Model):
    """The metadata result for the app, including available tables, etc.

    :param categories:
    :type categories: list[~azure.loganalytics.models.MetadataCategory]
    :param resource_types:
    :type resource_types:
     list[~azure.loganalytics.models.MetadataResourceType]
    :param solutions:
    :type solutions: list[~azure.loganalytics.models.MetadataSolution]
    :param tables:
    :type tables: list[~azure.loganalytics.models.MetadataTable]
    :param functions:
    :type functions: list[~azure.loganalytics.models.MetadataFunction]
    :param queries:
    :type queries: list[~azure.loganalytics.models.MetadataQuery]
    :param applications:
    :type applications: list[~azure.loganalytics.models.MetadataApplication]
    :param workspaces:
    :type workspaces: list[~azure.loganalytics.models.MetadataWorkspace]
    :param resources:
    :type resources: list[object]
    :param permissions:
    :type permissions: list[~azure.loganalytics.models.MetadataPermissions]
    """

    _validation = {
        'categories': {'unique': True},
        'resource_types': {'unique': True},
        'solutions': {'unique': True},
        'tables': {'unique': True},
        'functions': {'unique': True},
        'queries': {'unique': True},
        'applications': {'unique': True},
        'workspaces': {'unique': True},
        'resources': {'unique': True},
        'permissions': {'unique': True},
    }

    _attribute_map = {
        'categories': {'key': 'categories', 'type': '[MetadataCategory]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[MetadataResourceType]'},
        'solutions': {'key': 'solutions', 'type': '[MetadataSolution]'},
        'tables': {'key': 'tables', 'type': '[MetadataTable]'},
        'functions': {'key': 'functions', 'type': '[MetadataFunction]'},
        'queries': {'key': 'queries', 'type': '[MetadataQuery]'},
        'applications': {'key': 'applications', 'type': '[MetadataApplication]'},
        'workspaces': {'key': 'workspaces', 'type': '[MetadataWorkspace]'},
        'resources': {'key': 'resources', 'type': '[object]'},
        'permissions': {'key': 'permissions', 'type': '[MetadataPermissions]'},
    }

    def __init__(self, **kwargs):
        super(MetadataResults, self).__init__(**kwargs)
        self.categories = kwargs.get('categories', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.solutions = kwargs.get('solutions', None)
        self.tables = kwargs.get('tables', None)
        self.functions = kwargs.get('functions', None)
        self.queries = kwargs.get('queries', None)
        self.applications = kwargs.get('applications', None)
        self.workspaces = kwargs.get('workspaces', None)
        self.resources = kwargs.get('resources', None)
        self.permissions = kwargs.get('permissions', None)


class MetadataSolution(Model):
    """MetadataSolution.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param tags:
    :type tags: object
    :param properties:
    :type properties: object
    :param related: Required.
    :type related: ~azure.loganalytics.models.MetadataSolutionRelated
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'related': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'tags': {'key': 'tags', 'type': 'object'},
        'properties': {'key': 'properties', 'type': 'object'},
        'related': {'key': 'related', 'type': 'MetadataSolutionRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataSolution, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)
        self.related = kwargs.get('related', None)


class MetadataSolutionRelated(Model):
    """MetadataSolutionRelated.

    All required parameters must be populated in order to send to Azure.

    :param tables: Required.
    :type tables: list[str]
    :param functions:
    :type functions: list[str]
    :param categories:
    :type categories: list[str]
    :param queries:
    :type queries: list[str]
    :param workspaces:
    :type workspaces: list[str]
    """

    _validation = {
        'tables': {'required': True},
    }

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
        'categories': {'key': 'categories', 'type': '[str]'},
        'queries': {'key': 'queries', 'type': '[str]'},
        'workspaces': {'key': 'workspaces', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataSolutionRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.functions = kwargs.get('functions', None)
        self.categories = kwargs.get('categories', None)
        self.queries = kwargs.get('queries', None)
        self.workspaces = kwargs.get('workspaces', None)


class MetadataTable(Model):
    """MetadataTable.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param description:
    :type description: str
    :param timespan_column:
    :type timespan_column: str
    :param labels:
    :type labels: list[str]
    :param tags:
    :type tags: object
    :param properties:
    :type properties: object
    :param columns:
    :type columns: list[~azure.loganalytics.models.MetadataTableColumnsItem]
    :param related:
    :type related: ~azure.loganalytics.models.MetadataTableRelated
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'timespan_column': {'key': 'timespanColumn', 'type': 'str'},
        'labels': {'key': 'labels', 'type': '[str]'},
        'tags': {'key': 'tags', 'type': 'object'},
        'properties': {'key': 'properties', 'type': 'object'},
        'columns': {'key': 'columns', 'type': '[MetadataTableColumnsItem]'},
        'related': {'key': 'related', 'type': 'MetadataTableRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataTable, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.description = kwargs.get('description', None)
        self.timespan_column = kwargs.get('timespan_column', None)
        self.labels = kwargs.get('labels', None)
        self.tags = kwargs.get('tags', None)
        self.properties = kwargs.get('properties', None)
        self.columns = kwargs.get('columns', None)
        self.related = kwargs.get('related', None)


class MetadataTableColumnsItem(Model):
    """MetadataTableColumnsItem.

    All required parameters must be populated in order to send to Azure.

    :param name: Required.
    :type name: str
    :param description:
    :type description: str
    :param type: Required. Possible values include: 'bool', 'datetime',
     'dynamic', 'int', 'long', 'real', 'string'
    :type type: str or ~azure.loganalytics.models.MetadataColumnDataType
    :param is_preferred_facet:
    :type is_preferred_facet: bool
    :param source:
    :type source: object
    """

    _validation = {
        'name': {'required': True},
        'type': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'is_preferred_facet': {'key': 'isPreferredFacet', 'type': 'bool'},
        'source': {'key': 'source', 'type': 'object'},
    }

    def __init__(self, **kwargs):
        super(MetadataTableColumnsItem, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.description = kwargs.get('description', None)
        self.type = kwargs.get('type', None)
        self.is_preferred_facet = kwargs.get('is_preferred_facet', None)
        self.source = kwargs.get('source', None)


class MetadataTableRelated(Model):
    """MetadataTableRelated.

    :param categories:
    :type categories: list[str]
    :param solutions:
    :type solutions: list[str]
    :param resource_types:
    :type resource_types: list[str]
    :param workspaces:
    :type workspaces: list[str]
    :param functions:
    :type functions: list[str]
    :param queries:
    :type queries: list[str]
    """

    _attribute_map = {
        'categories': {'key': 'categories', 'type': '[str]'},
        'solutions': {'key': 'solutions', 'type': '[str]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[str]'},
        'workspaces': {'key': 'workspaces', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
        'queries': {'key': 'queries', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataTableRelated, self).__init__(**kwargs)
        self.categories = kwargs.get('categories', None)
        self.solutions = kwargs.get('solutions', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.workspaces = kwargs.get('workspaces', None)
        self.functions = kwargs.get('functions', None)
        self.queries = kwargs.get('queries', None)


class MetadataWorkspace(Model):
    """MetadataWorkspace.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param resource_id: Required.
    :type resource_id: str
    :param name: Required.
    :type name: str
    :param region: Required.
    :type region: str
    :param related:
    :type related: ~azure.loganalytics.models.MetadataWorkspaceRelated
    """

    _validation = {
        'id': {'required': True},
        'resource_id': {'required': True},
        'name': {'required': True},
        'region': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'region': {'key': 'region', 'type': 'str'},
        'related': {'key': 'related', 'type': 'MetadataWorkspaceRelated'},
    }

    def __init__(self, **kwargs):
        super(MetadataWorkspace, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.resource_id = kwargs.get('resource_id', None)
        self.name = kwargs.get('name', None)
        self.region = kwargs.get('region', None)
        self.related = kwargs.get('related', None)


class MetadataWorkspaceRelated(Model):
    """MetadataWorkspaceRelated.

    :param tables:
    :type tables: list[str]
    :param solutions:
    :type solutions: list[str]
    :param resource_types:
    :type resource_types: list[str]
    :param functions:
    :type functions: list[str]
    :param resources:
    :type resources: list[str]
    """

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[str]'},
        'solutions': {'key': 'solutions', 'type': '[str]'},
        'resource_types': {'key': 'resourceTypes', 'type': '[str]'},
        'functions': {'key': 'functions', 'type': '[str]'},
        'resources': {'key': 'resources', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(MetadataWorkspaceRelated, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)
        self.solutions = kwargs.get('solutions', None)
        self.resource_types = kwargs.get('resource_types', None)
        self.functions = kwargs.get('functions', None)
        self.resources = kwargs.get('resources', None)


class QueryBody(Model):
    """The Analytics query. Learn more about the [Analytics query
    syntax](https://azure.microsoft.com/documentation/articles/app-insights-analytics-reference/).

    All required parameters must be populated in order to send to Azure.

    :param query: Required. The query to execute.
    :type query: str
    :param timespan: Optional. The timespan over which to query data. This is
     an ISO8601 time period value.  This timespan is applied in addition to any
     that are specified in the query expression.
    :type timespan: str
    :param workspaces: A list of workspaces that are included in the query.
    :type workspaces: list[str]
    """

    _validation = {
        'query': {'required': True},
    }

    _attribute_map = {
        'query': {'key': 'query', 'type': 'str'},
        'timespan': {'key': 'timespan', 'type': 'str'},
        'workspaces': {'key': 'workspaces', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(QueryBody, self).__init__(**kwargs)
        self.query = kwargs.get('query', None)
        self.timespan = kwargs.get('timespan', None)
        self.workspaces = kwargs.get('workspaces', None)


class QueryResults(Model):
    """A query response.

    Contains the tables, columns & rows resulting from a query.

    All required parameters must be populated in order to send to Azure.

    :param tables: Required. The list of tables, columns and rows.
    :type tables: list[~azure.loganalytics.models.Table]
    """

    _validation = {
        'tables': {'required': True},
    }

    _attribute_map = {
        'tables': {'key': 'tables', 'type': '[Table]'},
    }

    def __init__(self, **kwargs):
        super(QueryResults, self).__init__(**kwargs)
        self.tables = kwargs.get('tables', None)


class Table(Model):
    """A query response table.

    Contains the columns and rows for one table in a query response.

    All required parameters must be populated in order to send to Azure.

    :param name: Required. The name of the table.
    :type name: str
    :param columns: Required. The list of columns in this table.
    :type columns: list[~azure.loganalytics.models.Column]
    :param rows: Required. The resulting rows from this query.
    :type rows: list[list[object]]
    """

    _validation = {
        'name': {'required': True},
        'columns': {'required': True},
        'rows': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'columns': {'key': 'columns', 'type': '[Column]'},
        'rows': {'key': 'rows', 'type': '[[object]]'},
    }

    def __init__(self, **kwargs):
        super(Table, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.columns = kwargs.get('columns', None)
        self.rows = kwargs.get('rows', None)
