# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer

from ._configuration import SubscriptionClientConfiguration
from .operations import PurchaseSupportStatusOperations
from .operations import SupportPlansOperations
from .operations import SupportPlanDefaultOperations
from .operations import PurchaseSupportPlanOperations
from . import models


class SubscriptionClient(SDKClient):
    """Subscription client provides an interface to create and manage Azure subscriptions programmatically.

    :ivar config: Configuration for client.
    :vartype config: SubscriptionClientConfiguration

    :ivar purchase_support_status: PurchaseSupportStatus operations
    :vartype purchase_support_status: azure.mgmt.subscription.operations.PurchaseSupportStatusOperations
    :ivar support_plans: SupportPlans operations
    :vartype support_plans: azure.mgmt.subscription.operations.SupportPlansOperations
    :ivar support_plan_default: SupportPlanDefault operations
    :vartype support_plan_default: azure.mgmt.subscription.operations.SupportPlanDefaultOperations
    :ivar purchase_support_plan: PurchaseSupportPlan operations
    :vartype purchase_support_plan: azure.mgmt.subscription.operations.PurchaseSupportPlanOperations

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, base_url=None):

        self.config = SubscriptionClientConfiguration(credentials, base_url)
        super(SubscriptionClient, self).__init__(self.config.credentials, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2019-10-01-preview'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.purchase_support_status = PurchaseSupportStatusOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.support_plans = SupportPlansOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.support_plan_default = SupportPlanDefaultOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.purchase_support_plan = PurchaseSupportPlanOperations(
            self._client, self.config, self._serialize, self._deserialize)
