# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import DefaultSupportPlanResponseResult
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import OperationListResult
    from ._models_py3 import ProxyResource
    from ._models_py3 import PurchaseSupportResponseResult
    from ._models_py3 import SupportPlanName
except (SyntaxError, ImportError):
    from ._models import DefaultSupportPlanResponseResult
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import Operation
    from ._models import OperationDisplay
    from ._models import OperationListResult
    from ._models import ProxyResource
    from ._models import PurchaseSupportResponseResult
    from ._models import SupportPlanName
from ._paged_models import DefaultSupportPlanResponseResultPaged
from ._subscription_client_enums import (
    SupportPlanType,
)

__all__ = [
    'DefaultSupportPlanResponseResult',
    'ErrorResponse', 'ErrorResponseException',
    'Operation',
    'OperationDisplay',
    'OperationListResult',
    'ProxyResource',
    'PurchaseSupportResponseResult',
    'SupportPlanName',
    'DefaultSupportPlanResponseResultPaged',
    'SupportPlanType',
]
